import { Product } from './types';

export const categories = [
  'All',
  'Lighting',
  'Furniture',
  'Audio',
  'Smart Home',
  'Computers',
  'Kitchen',
  'Home Decor',
  'Electronics',
  'Home Office',
  'Fitness',
  'Outdoor',
  'Gaming',
  'Accessories',
  'Personal Care',
  'Bathroom',
  'Bedding',
  'Home Appliances'
];

export const getProductById = (id: string): Product | undefined => {
  return products.find(product => product.id === id);
};

export const getProductsByCategory = (category: string): Product[] => {
  if (category === 'All') {
    return products;
  }
  return products.filter(product => product.category === category);
};

export const getFeaturedProducts = (): Product[] => {
  return products.filter(product => product.featured);
};

export const products: Product[] = [
  {
    id: '1',
    name: 'Minimalist Desk Lamp',
    description: 'A sleek, adjustable desk lamp with touch controls and multiple brightness settings. Perfect for your minimalist workspace.',
    price: 129.99,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Lighting',
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Ergonomic Office Chair',
    description: 'Premium ergonomic chair with lumbar support, adjustable armrests, and breathable mesh back for all-day comfort.',
    price: 349.99,
    images: [
      'https://images.unsplash.com/photo-1505843490701-5c4b83b47dc3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Furniture',
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Bluetooth Noise-Cancelling Headphones',
    description: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and exceptional sound quality.',
    price: 249.99,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Audio',
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Smart Home Hub',
    description: 'Central control unit for your smart home devices. Connects with lights, thermostats, security systems, and more.',
    price: 199.99,
    images: [
      'https://images.unsplash.com/photo-1558089687-f282ffcbc0d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Smart Home',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '5',
    name: 'Ultra-Thin Laptop',
    description: 'Powerful yet lightweight laptop with 14-inch 4K display, 16GB RAM, 512GB SSD, and all-day battery life.',
    price: 1299.99,
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Computers',
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: '6',
    name: 'Ceramic Pour-Over Coffee Set',
    description: 'Handcrafted ceramic pour-over coffee maker with matching cups. The perfect ritual for coffee enthusiasts.',
    price: 89.99,
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '7',
    name: 'Minimalist Wall Clock',
    description: 'Simple, elegant wall clock with a brushed aluminum frame and silent movement. A statement piece for any room.',
    price: 59.99,
    images: [
      'https://images.unsplash.com/photo-1507646227500-4d389b0012be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '8',
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices. Sleek design with LED charging indicator.',
    price: 39.99,
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Electronics',
    featured: false,
    inStock: true,
    rating: 4.4,
  },
  {
    id: '9',
    name: 'Smart Floor Lamp',
    description: 'Wi-Fi-connected floor lamp with color-changing capabilities, adjustable brightness, and voice control compatibility.',
    price: 179.99,
    images: [
      'https://images.unsplash.com/photo-1540932239986-30128078f3c5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Lighting',
    featured: false,
    inStock: true,
    rating: 4.3,
  },
  {
    id: '10',
    name: 'Pendant Light Fixture',
    description: 'Modern pendant light with adjustable height, perfect for dining areas or kitchen islands. Brushed brass finish.',
    price: 149.99,
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Lighting',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '11',
    name: 'Solar Garden Lights (Set of 6)',
    description: 'Weather-resistant solar-powered garden lights that automatically illuminate at dusk, creating ambient outdoor lighting.',
    price: 79.99,
    images: [
      'https://images.unsplash.com/photo-1558089687-f282ffcbc0d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Lighting',
    featured: false,
    inStock: true,
    rating: 4.2,
  },
  {
    id: '12',
    name: 'Modular Sectional Sofa',
    description: 'Versatile modular sofa that can be arranged in multiple configurations. Features durable fabric upholstery and solid wood legs.',
    price: 1299.99,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Furniture',
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '13',
    name: 'Mid-Century Coffee Table',
    description: 'Elegant coffee table featuring walnut veneer and tapered legs. The perfect centerpiece for your living room.',
    price: 299.99,
    images: [
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Furniture',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '14',
    name: 'Standing Desk',
    description: 'Electric height-adjustable standing desk with memory presets and anti-collision technology. Promotes a healthier work environment.',
    price: 459.99,
    images: [
      'https://images.unsplash.com/photo-1544200175-cfacb60ad546?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Furniture',
    featured: false,
    inStock: true,
    rating: 4.9,
  },
  {
    id: '15',
    name: 'Minimalist Bookshelf',
    description: 'Open-back bookshelf with a sleek, minimalist design. Features five shelves for ample storage and display space.',
    price: 229.99,
    images: [
      'https://images.unsplash.com/photo-1544457070-4cd773b4d71e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Furniture',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '16',
    name: 'Portable Bluetooth Speaker',
    description: 'Compact, water-resistant Bluetooth speaker with 20-hour battery life, perfect for outdoor adventures or poolside relaxation.',
    price: 129.99,
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Audio',
    featured: false,
    inStock: true,
    rating: 4.4,
  },
  {
    id: '17',
    name: 'Wireless Earbuds',
    description: 'True wireless earbuds with active noise cancellation, touch controls, and a charging case that provides up to 24 hours of total playtime.',
    price: 149.99,
    images: [
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f37?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Audio',
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '18',
    name: 'Premium Soundbar',
    description: 'Immersive 5.1 channel soundbar with wireless subwoofer, Dolby Atmos support, and 4K pass-through for a cinematic audio experience.',
    price: 399.99,
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Audio',
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '19',
    name: 'Smart Thermostat',
    description: 'Wi-Fi-connected thermostat that learns your preferences and automatically adjusts to save energy while maintaining comfort.',
    price: 249.99,
    images: [
      'https://images.unsplash.com/photo-1621269797232-709d3ad2eea7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Smart Home',
    featured: false,
    inStock: true,
    rating: 4.9,
  },
  {
    id: '20',
    name: 'Video Doorbell',
    description: 'HD video doorbell with two-way audio, motion detection, and night vision. Connects to your smartphone for real-time alerts.',
    price: 179.99,
    images: [
      'https://images.unsplash.com/photo-1588974874022-39e5cd8e66ac?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Smart Home',
    featured: true,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '21',
    name: 'Smart Light Bulb Set (4-Pack)',
    description: 'Color-changing smart bulbs compatible with voice assistants. Create schedules and scenes for the perfect ambiance.',
    price: 89.99,
    images: [
      'https://images.unsplash.com/photo-1586473219010-2ffc57b0d282?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Smart Home',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '22',
    name: 'Robot Vacuum Cleaner',
    description: 'Smart robot vacuum with mapping technology, powerful suction, and self-emptying dustbin. Schedule cleanings through the companion app.',
    price: 399.99,
    images: [
      'https://images.unsplash.com/photo-1684483871399-9a89f5e525a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Smart Home',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '23',
    name: 'Mechanical Keyboard',
    description: 'Customizable mechanical keyboard with RGB backlighting, programmable keys, and hot-swappable switches for a personalized typing experience.',
    price: 149.99,
    images: [
      'https://images.unsplash.com/photo-1595044426077-d36d9236d44a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Computers',
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '24',
    name: 'Ultrawide Monitor',
    description: '34-inch curved ultrawide monitor with 3440x1440 resolution, 144Hz refresh rate, and HDR support for immersive gaming and productivity.',
    price: 699.99,
    images: [
      'https://images.unsplash.com/photo-1593642634367-d91a135587b5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Computers',
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: '25',
    name: 'Gaming Mouse',
    description: 'High-precision gaming mouse with adjustable DPI, programmable buttons, and ergonomic design for extended gaming sessions.',
    price: 79.99,
    images: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Computers',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '26',
    name: 'External SSD (1TB)',
    description: 'Ultra-fast external SSD with 1TB storage capacity, compact design, and USB-C connectivity for quick file transfers.',
    price: 169.99,
    images: [
      'https://images.unsplash.com/photo-1581368135153-a506c61ea9bc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Computers',
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '27',
    name: 'Smart Blender',
    description: 'High-performance blender with pre-programmed settings and variable speed control. Perfect for smoothies, soups, and more.',
    price: 199.99,
    images: [
      'https://images.unsplash.com/photo-1622993549645-0c3bdecb35eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '28',
    name: 'Cast Iron Cookware Set',
    description: '5-piece enameled cast iron cookware set including dutch oven, skillet, and grill pan. Pre-seasoned and ready to use.',
    price: 299.99,
    images: [
      'https://images.unsplash.com/photo-1585238342024-78d387f4a707?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: '29',
    name: 'Cold Brew Coffee Maker',
    description: 'Glass cold brew maker with stainless steel filter. Makes smooth, low-acid coffee concentrate for up to 7 days of delicious cold brew.',
    price: 49.99,
    images: [
      'https://images.unsplash.com/photo-1570087935831-0bce67a2c3a7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '30',
    name: 'Professional Chef\'s Knife',
    description: 'High-carbon stainless steel 8-inch chef\'s knife with ergonomic handle. Precision-forged for balance and durability.',
    price: 129.99,
    images: [
      'https://images.unsplash.com/photo-1593618998160-854bc2be0c21?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '31',
    name: 'Abstract Canvas Wall Art',
    description: 'Set of 3 abstract canvas prints with floating frame, adding a contemporary touch to any room. Each piece measures 16"x24".',
    price: 159.99,
    images: [
      'https://images.unsplash.com/photo-1531985838078-501f5591a5e9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '32',
    name: 'Macrame Wall Hanging',
    description: 'Handcrafted macrame wall hanging made from 100% cotton rope. Each piece is unique and adds texture to your wall decor.',
    price: 79.99,
    images: [
      'https://images.unsplash.com/photo-1622163642998-74ea921c0e55?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '33',
    name: 'Geometric Area Rug (5\'x8\')',
    description: 'Contemporary geometric pattern rug with soft, plush texture. Stain-resistant and durable for high-traffic areas.',
    price: 249.99,
    images: [
      'https://images.unsplash.com/photo-1617791160505-6f00504e3519?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '34',
    name: 'Ceramic Planter Set',
    description: 'Set of 3 minimalist ceramic planters in varying sizes, perfect for succulents, herbs, or small houseplants.',
    price: 69.99,
    images: [
      'https://images.unsplash.com/photo-1623910394425-5700f5594786?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '35',
    name: 'Smartphone Gimbal Stabilizer',
    description: 'Three-axis gimbal stabilizer with tracking features and extended battery life for professional-looking smartphone videos.',
    price: 129.99,
    images: [
      'https://images.unsplash.com/photo-1595587637401-47fd84d5baff?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Electronics',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '36',
    name: 'Digital Photo Frame',
    description: '10.1-inch HD digital photo frame with Wi-Fi connectivity. Upload photos remotely and create slideshows of your favorite moments.',
    price: 159.99,
    images: [
      'https://images.unsplash.com/photo-1595044426062-74d3cec86e9d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Electronics',
    featured: true,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '37',
    name: 'Portable Power Bank (20000mAh)',
    description: 'High-capacity power bank with fast charging support, dual USB ports, and USB-C input/output. Charge multiple devices on the go.',
    price: 59.99,
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB
