
import { Product } from './types';

export const products50To100: Product[] = [
  {
    id: '51',
    name: 'Gaming Controller',
    description: 'Pro gaming controller with customizable buttons, hair triggers, and extended battery life for competitive gaming advantage.',
    price: 169.99,
    images: [
      'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Gaming',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '52',
    name: 'Gaming Headset',
    description: 'Immersive gaming headset with surround sound, noise-cancelling microphone, and memory foam ear cushions for extended gaming sessions.',
    price: 129.99,
    images: [
      'https://images.unsplash.com/photo-1615655114865-4cc5c5c095b9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Gaming',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '53',
    name: 'Leather Watch',
    description: 'Classic analog watch with genuine leather strap, sapphire crystal face, and Japanese movement. Timeless accessory for any outfit.',
    price: 199.99,
    images: [
      'https://images.unsplash.com/photo-1539874754764-5a96559165b0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Accessories',
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '54',
    name: 'Designer Sunglasses',
    description: 'Polarized sunglasses with UV protection, lightweight frame, and premium case. Combines style and functionality for everyday wear.',
    price: 149.99,
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Accessories',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '55',
    name: 'Leather Wallet',
    description: 'Slim bifold wallet crafted from full-grain leather with RFID blocking technology. Features multiple card slots and bill compartment.',
    price: 79.99,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Accessories',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '56',
    name: 'Electric Toothbrush',
    description: 'Sonic electric toothbrush with multiple cleaning modes, pressure sensor, and travel case. Removes up to 10x more plaque than manual brushes.',
    price: 99.99,
    images: [
      'https://images.unsplash.com/photo-1559591937-c611173b553d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Personal Care',
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '57',
    name: 'Facial Skincare Set',
    description: 'Complete skincare regimen including cleanser, toner, serum, and moisturizer formulated with natural ingredients for radiant skin.',
    price: 129.99,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Personal Care',
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '58',
    name: 'Hair Styling Tools Set',
    description: 'Professional-grade hair dryer, straightener, and curling wand with ceramic technology and multiple heat settings for versatile styling.',
    price: 159.99,
    images: [
      'https://images.unsplash.com/photo-1522338140262-f46f5913618a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Personal Care',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '59',
    name: 'Rainfall Shower Head',
    description: 'Luxury 10-inch rainfall shower head with high-pressure water flow system and easy installation. Creates a spa-like shower experience.',
    price: 89.99,
    images: [
      'https://images.unsplash.com/photo-1507272931001-fc94ae386abb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Bathroom',
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '60',
    name: 'Bathroom Vanity Cabinet',
    description: 'Modern bathroom vanity with soft-close drawers, ceramic sink, and marble countertop. Includes pre-drilled faucet holes for easy installation.',
    price: 599.99,
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Bathroom',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '61',
    name: 'Towel Set (6-Piece)',
    description: 'Luxury 100% Egyptian cotton towel set including 2 bath towels, 2 hand towels, and 2 washcloths. Soft, absorbent, and quick-drying.',
    price: 79.99,
    images: [
      'https://images.unsplash.com/photo-1563291074-2bf8677ac0e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Bathroom',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '62',
    name: 'Luxury Duvet Cover Set',
    description: '1000-thread-count Egyptian cotton duvet cover set with two pillow shams. Breathable fabric for year-round comfort and luxury.',
    price: 199.99,
    images: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Bedding',
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: '63',
    name: 'Memory Foam Mattress',
    description: 'Queen-size memory foam mattress with cooling gel technology and pressure-relieving support layers for restorative sleep.',
    price: 899.99,
    images: [
      'https://images.unsplash.com/photo-1601026909629-bad5e1f5d3fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Bedding',
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '64',
    name: 'Weighted Blanket',
    description: '15-pound weighted blanket with plush, removable cover. Promotes deeper sleep and reduces anxiety through gentle, even pressure.',
    price: 119.99,
    images: [
      'https://images.unsplash.com/photo-1631756964162-25c8c07579b1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Bedding',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '65',
    name: 'Smart Refrigerator',
    description: 'French door refrigerator with touchscreen, interior cameras, and smart connectivity. Alerts you when food is expiring and suggests recipes.',
    price: 2499.99,
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Appliances',
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '66',
    name: 'Cordless Stick Vacuum',
    description: 'Lightweight cordless vacuum with powerful suction, HEPA filtration, and convertible handheld function for versatile whole-home cleaning.',
    price: 349.99,
    images: [
      'https://images.unsplash.com/photo-1584992236310-6aded19d2947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Appliances',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '67',
    name: 'Espresso Machine',
    description: 'Semi-automatic espresso machine with built-in grinder, milk frother, and programmable brewing options for café-quality coffee at home.',
    price: 699.99,
    images: [
      'https://images.unsplash.com/photo-1595246134776-8c686ea0e709?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Appliances',
    featured: false,
    inStock: true,
    rating: 4.9,
  },
  {
    id: '68',
    name: 'Air Purifier',
    description: 'HEPA air purifier with activated carbon filter removes 99.97% of airborne particles, allergens, and odors. Covers rooms up to 500 sq ft.',
    price: 229.99,
    images: [
      'https://images.unsplash.com/photo-1605374011147-9c881ad43ff7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Appliances',
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '69',
    name: 'Ceramic Plant Pot Set',
    description: 'Set of 3 minimalist ceramic planters in varying sizes with drainage holes and bamboo trays. Perfect for indoor plants and herbs.',
    price: 49.99,
    images: [
      'https://images.unsplash.com/photo-1485955900006-10f4d324d411?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '70',
    name: 'Bamboo Bath Caddy',
    description: 'Expandable bamboo bath tray with slots for wine glass, book, tablet, phone, and other bath essentials for luxurious relaxation.',
    price: 39.99,
    images: [
      'https://images.unsplash.com/photo-1617623251701-d860dba4b97c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Bathroom',
    featured: false,
    inStock: true,
    rating: 4.4,
  },
  {
    id: '71',
    name: 'Marble Cheese Board',
    description: 'Elegant white marble cheese board with acacia wood accent. Comes with 3 cheese knives for perfect entertaining and serving.',
    price: 59.99,
    images: [
      'https://images.unsplash.com/photo-1536237717588-c7627572caa3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '72',
    name: 'Smart Indoor Garden',
    description: 'Self-watering indoor garden with built-in grow lights and app control. Grow fresh herbs and vegetables year-round in your kitchen.',
    price: 199.99,
    images: [
      'https://images.unsplash.com/photo-1590621819878-3fa04733d3df?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '73',
    name: 'Wireless Charging Stand',
    description: '3-in-1 wireless charging station for smartphone, smartwatch, and earbuds. Fast-charging capability with sleek aluminum design.',
    price: 79.99,
    images: [
      'https://images.unsplash.com/photo-1636320941116-a2eee4a42836?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Electronics',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '74',
    name: 'Portable Bluetooth Printer',
    description: 'Compact, rechargeable photo printer that connects via Bluetooth to print photos directly from your smartphone or tablet.',
    price: 129.99,
    images: [
      'https://images.unsplash.com/photo-1612815771286-38ef85e80d56?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Electronics',
    featured: false,
    inStock: true,
    rating: 4.3,
  },
  {
    id: '75',
    name: 'Glass Food Storage Set',
    description: '10-piece glass food storage container set with locking lids. Microwave, freezer, and dishwasher safe for versatile food storage.',
    price: 49.99,
    images: [
      'https://images.unsplash.com/photo-1606771694705-092cb894257f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: false,
    inStock: true,
    rating: 4.6,
  }
];
