
import { Product } from './types';

export const products75To100: Product[] = [
  {
    id: '76',
    name: 'Handwoven Throw Blanket',
    description: 'Soft, handwoven throw blanket made from 100% cotton. Perfect accent piece for your sofa or bed, providing both style and comfort.',
    price: 89.99,
    images: [
      'https://images.unsplash.com/photo-1580999246902-21e758685b3f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '77',
    name: 'Modern Wall Mirror',
    description: 'Round wall mirror with brass frame, adds light and dimension to any room. Includes hanging hardware for easy installation.',
    price: 129.99,
    images: [
      'https://images.unsplash.com/photo-1618220252344-8ec99ec2aa31?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '78',
    name: 'Wireless Doorbell',
    description: 'Water-resistant wireless doorbell with 1000ft range, 58 chimes, and visual alerts. Easy installation with no wiring required.',
    price: 39.99,
    images: [
      'https://images.unsplash.com/photo-1582139329536-e7dd40ca58db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Smart Home',
    featured: false,
    inStock: true,
    rating: 4.4,
  },
  {
    id: '79',
    name: 'Smart Water Bottle',
    description: 'Insulated water bottle that tracks hydration levels, glows to remind you to drink, and syncs with fitness apps via Bluetooth.',
    price: 59.99,
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Fitness',
    featured: false,
    inStock: true,
    rating: 4.3,
  },
  {
    id: '80',
    name: 'Wireless Earbuds Pro',
    description: 'Premium true wireless earbuds with spatial audio, active noise cancellation, and sweat resistance. Perfect for workouts and commuting.',
    price: 199.99,
    images: [
      'https://images.unsplash.com/photo-1590658268037-7e63a24a4a14?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Audio',
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: '81',
    name: 'Home Theatre System',
    description: '5.1 channel home theatre system with wireless subwoofer, Bluetooth connectivity, and 4K pass-through for immersive entertainment.',
    price: 599.99,
    images: [
      'https://images.unsplash.com/photo-1558888401-3cc1de77652d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Audio',
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '82',
    name: 'Wireless Keyboard and Mouse',
    description: 'Ergonomic wireless keyboard and mouse combo with long battery life and precise tracking. Compatible with all major operating systems.',
    price: 79.99,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Computers',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '83',
    name: 'Leather Travel Bag',
    description: 'Full-grain leather weekender bag with spacious interior, multiple compartments, and comfortable shoulder strap. Perfect for short trips.',
    price: 229.99,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Accessories',
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '84',
    name: 'Indoor Exercise Bike',
    description: 'Stationary exercise bike with magnetic resistance, LCD display, and adjustable seat. Quiet operation for apartment-friendly workouts.',
    price: 399.99,
    images: [
      'https://images.unsplash.com/photo-1540539234-c14a20fb7c7b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Fitness',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '85',
    name: 'Robot Lawn Mower',
    description: 'Autonomous lawn mower with GPS navigation, rain sensors, and app control. Keeps your lawn perfectly manicured with minimal effort.',
    price: 999.99,
    images: [
      'https://images.unsplash.com/photo-1589365278144-c9e705f843ba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Outdoor',
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '86',
    name: 'Modular Shelving System',
    description: 'Customizable wall-mounted shelving system with interchangeable components. Create the perfect storage solution for any space.',
    price: 179.99,
    images: [
      'https://images.unsplash.com/photo-1595428774223-ef52624120d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Furniture',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '87',
    name: 'Smart Door Lock',
    description: 'Keyless entry door lock with fingerprint scanner, keypad, and smartphone control. Monitor access and grant temporary entry remotely.',
    price: 249.99,
    images: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Smart Home',
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '88',
    name: 'Smokeless Indoor Grill',
    description: 'Electric indoor grill with temperature control and smoke-extraction technology. Enjoy grilled food year-round without smoke or odors.',
    price: 179.99,
    images: [
      'https://images.unsplash.com/photo-1555507036-ab1f4038808a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '89',
    name: 'Designer Table Lamp',
    description: 'Modern table lamp with adjustable arm, dimmable LED light, and USB charging port. Perfect for bedside tables or desk lighting.',
    price: 129.99,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Lighting',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '90',
    name: 'Wool Area Rug (8x10)',
    description: 'Hand-tufted 100% wool area rug with contemporary design. Adds warmth, texture, and style to living spaces and bedrooms.',
    price: 499.99,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '91',
    name: 'Adjustable Laptop Stand',
    description: 'Ergonomic aluminum laptop stand with adjustable height and angle. Improves posture and keeps your device cool during use.',
    price: 69.99,
    images: [
      'https://images.unsplash.com/photo-1611174797136-5e32170563d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Office',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '92',
    name: 'Smart Coffee Maker',
    description: 'Programmable coffee maker with smartphone control, customizable brewing strength, and built-in grinder for fresh coffee every morning.',
    price: 199.99,
    images: [
      'https://images.unsplash.com/photo-1608354580875-30bd4168b351?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Kitchen',
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '93',
    name: 'Luxury Pillow Set',
    description: 'Set of 2 hotel-quality down alternative pillows with 100% cotton covers. Medium-firm support for side and back sleepers.',
    price: 99.99,
    images: [
      'https://images.unsplash.com/photo-1631455734729-bc766b5f4f39?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Bedding',
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: '94',
    name: 'Gaming Mouse Pad (XL)',
    description: 'Extra-large gaming mouse pad with smooth surface, non-slip rubber base, and stitched edges for durability during intense gaming sessions.',
    price: 29.99,
    images: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Gaming',
    featured: false,
    inStock: true,
    rating: 4.5,
  },
  {
    id: '95',
    name: 'Outdoor String Lights',
    description: '48ft weatherproof LED string lights with dimmable Edison bulbs. Create a cozy ambiance for patios, gardens, and outdoor entertaining.',
    price: 59.99,
    images: [
      'https://images.unsplash.com/photo-1565844681319-9462b3e8b85f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Outdoor',
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '96',
    name: 'Tablet Stand Holder',
    description: 'Adjustable tablet stand compatible with all tablets and e-readers. Perfect for hands-free viewing, video calls, and recipe reading.',
    price: 34.99,
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Accessories',
    featured: false,
    inStock: true,
    rating: 4.4,
  },
  {
    id: '97',
    name: 'Aromatherapy Diffuser',
    description: 'Ultrasonic essential oil diffuser with LED mood lighting, automatic shut-off, and multiple mist settings for relaxation and air freshening.',
    price: 49.99,
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Decor',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '98',
    name: 'Bluetooth Turntable',
    description: 'Modern vinyl record player with Bluetooth connectivity, built-in speakers, and USB recording capability. Combines vintage charm with modern tech.',
    price: 179.99,
    images: [
      'https://images.unsplash.com/photo-1516481071949-6a4a9bc25ec9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Audio',
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: '99',
    name: 'Smart Pet Feeder',
    description: 'Automatic pet feeder with programmable meal times, portion control, and smartphone monitoring. Includes built-in camera to check on your pet.',
    price: 159.99,
    images: [
      'https://images.unsplash.com/photo-1598970434795-0c54fe7c0648?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Smart Home',
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: '100',
    name: 'Modern Desk Organizer',
    description: 'Stylish desk organizer with compartments for office supplies, phone holder, and cable management. Keeps workspace tidy and efficient.',
    price: 44.99,
    images: [
      'https://images.unsplash.com/photo-1544247341-d3128e8a819b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Home Office',
    featured: false,
    inStock: true,
    rating: 4.5,
  }
];
